version: '3.4'

services:
  sut:
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    #   target: runner
    image:
      "eds-collabora/debos:${SHA}"      
    volumes:
      - type: bind
        source: ../tests
        target: /recipes
    working_dir: /recipes
    entrypoint: ./tests.sh
    command: --disable-fakemachine
