version: '3.4'

services:
  sut:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image:
      eds-collabora/debos
    volumes:
      - type: bind
        source: ../tests
        target: /recipes
    working_dir: /recipes
    entrypoint: ./tests.sh
    command: --disable-fakemachine
