version: '3.4'

services:
  sut:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder
    image:
      "${IMAGE}"
    working_dir: /usr/local/go/src/github.com/go-debos/debos
    command: go test -v ./...
