name: Build Debos and run tests
on: [pull_request, push]

jobs:
  build-test:
    name: Build Debos and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/arm64
          - linux/amd64
          - linux/386
      fail-fast: false
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup buildx
        id: build
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses:  docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false

      - name: Unit Test
        run: |
          docker-compose -f docker/unit-tests.test.yml \
            up --build --exit-code-from=sut

      - name: Run test recipes on host
        run: |
          docker-compose -f docker/recipes.test.yml \
            up --build --exit-code-from=sut
